 VarDescription_Exp12Metamers={
                    'exp: Experiment Name',
               '    date: current date when exp was run',
                    'time: time when exp was run',
                     'sid: subjectID',
                    'trial: trial number',
                     'block: block number',
                 'trialType: index from randomization matrix, not important, sorry',
                   'congNum: 1=uniform (congruent), 2=mixed (incongruent)',
             'conditionName: names for congNum',
                   'stimNum: stimuli index number (1:30 for each category), attn there are 2 diff stim for each number (big and small)',
                    'setSize: num of items presented including target'
         'currImNum(numeric):  All stimuli presented (1:30 by each category), used in conjunction with currImType, different from usage imported from I struct in Exp3',
        'currImType(numeric): IMPORTED FROM I struct: all stimuli categories (targ and dist), 1=big targ, 2-small targ',
            'targIm(numeric): target index number, should be 1-num of stim per category (30). Careful as targImNum=30 could be different images if sizeNum=1 or 2',
           'currPos(numeric): current position of each item',
         'targetPos(numeric): position of the target (should be the first number in currPos',
                      'currA: Angular position of the item numbers in currImNum',
                      'currX: X position of the item numbers in currImNum',
                      'currY: Y position of the item numbers in currImNum',  
         'respKeyNum(numeric: number of response key (spacebar index usually)',
           'respKeyName(cell): response key name',
        'respCorrect(numeric): did they click on the correct image',
             'respRT(numeric): spacebarpress RT',
          'respError(numeric): 1 if error, 0 if correct',
     'wholeTrialTime(numeric): time in s from preview to click finish '
            'sizeNum(numeric): Real-world size of search target (1=Big, 2=Small)',
'clickLoc(numeric): what position did subjects click on ',
          'clickItem(numeric): what item did subjects click on]',
            'clickRT(numeric): how long did it take to click'}